spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component:Product Service

---

Spring:
  config:
    activate:
      on-profile: localhost

  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: deneme
  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 12345